# Generated by Django 6.0.2 on 2026-06-11 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CRE', 'Creó'), ('MOD', 'Modificó'), ('ELI', 'Eliminó'), ('CAM', 'Cambió estado'), ('VER', 'Verificó')], max_length=3, verbose_name='Acción')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('datos_antes', models.JSONField(blank=True, null=True, verbose_name='Datos antes')),
                ('datos_despues', models.JSONField(blank=True, null=True, verbose_name='Datos después')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['modelo', 'objeto_id'], name='auditorias__modelo_73382c_idx'), models.Index(fields=['usuario'], name='auditorias__usuario_4d8bf3_idx'), models.Index(fields=['-created_at'], name='auditorias__created_6340fc_idx')],
            },
        ),
    ]
